source 'https://github.com/cocoaPods/specs.git'
platform :ios, '8.0'
use_frameworks!
target "Moments" do
  pod 'Masonry'
  pod 'BlocksKit'
  pod 'DZNEmptyDataSet'
  pod 'QMUIKit'
  pod 'ReactiveObjC'
  pod 'STPopup'
  pod 'MJRefresh'
  pod 'MJExtension'
  pod 'SDWebImage'
  pod 'TZImagePickerController'
  pod 'TPKeyboardAvoiding'
  pod 'TBActionSheet'
  pod 'Realm'
#  pod 'Firebase/Core'
#  pod 'Firebase/AdMob'
  pod 'Google-Mobile-Ads-SDK'
  pod 'XLForm'
end
